name: teuton_feature
description: >
  A CLI tool to generate Flutter features with Clean Architecture, Cubit state management, 
  and GetIt dependency injection — instantly.
version: 1.2.0

repository: https://github.com/teutones92/teuton_feature
homepage: https://teutondev.com/
issue_tracker: https://github.com/teutones92/teuton_feature/issues
documentation: https://pub.dev/documentation/teuton_feature/latest/

environment:
  sdk: '>=3.0.0'

dependencies:
  ansicolor: ^2.0.2
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

executables:
  teuton_feature:

topics:
  - cli
  - flutter
  - clean-architecture
  - cubit
  - getit

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2
