name: teuton_feature
description: CLI tool for generating Flutter Clean Architecture features with Cubit and GetIt.
version: 1.1.0
repository: https://github.com/teutones92/teuton_feature
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  args: ^2.5.0

executables:
  teuton_feature: bin/teuton_feature.dart
